### ISSUE TITLE
Minor loading issue with ActiveJob

### ISSUE THREAD

**Issue by pkopac** [sidekiq/sidekiq#6602]
Ruby version: 3.3.4
Rails version: 7.0.8.5
Sidekiq / Pro / Enterprise version(s): Sidekiq 7.3.8

This particular problem was not present in 7.3.1 and was introduced with #6430.

I got this error:
```
NoMethodError:
  undefined method `lookup' for module ActiveJob::QueueAdapters
# /home/developer/.gem/ruby/3.3.0/gems/activejob-7.0.8.5/lib/active_job/queue_adapter.rb:41:in `queue_adapter='
```

when calling `require 'rspec/rails'` in test setup.

It seems Rails/Zeitwerk encounter the Sidekiq module definition first and don't bother loading the original one. Adding `require 'active_job/queue_adapters'` fixes this, but it's unexpected. It only happens in `test` environment.

**Comment by bibendi** [comment]
Same issue

**Comment by mperham** [comment]
7.3.9 released, let me know if it doesn't fix your issue.
