### ISSUE TITLE
Sidekiq::Client.push_bulk not working with ActiveJob and Sidekiq 7.3+

### ISSUE THREAD

**Issue by cenavarro** [sidekiq/sidekiq#6575]
Upgrading from Sidekiq 7.2.x to 7.3.x and using `Sidekiq::Client.push_bulk` raises an error when executing the job.

We have code like this:

```ruby
users.in_batches do |group|
  ids = group.pluck(:id)
  job_args = ids.map { |x| [x] }
  Sidekiq::Client.push_bulk("class" => RegeneratePassJob, "args" => job_args)
end
```

The jobs are inserted well in the queue but when executing them raises the following error:

```
pid=14550 tid=11d6 WARN: NoMethodError: undefined method `_context=' for an instance of RegeneratePassJob
```

The `RegeneratePassJob` is not a `Sidekiq::Job`, it is a `ActiveJob::Base` class. It looks like this:

```ruby
class RegeneratePassJob < ApplicationJob
  def perform(user_id)
    ...
  end
end
```

If we migrate from `ApplicationJob` to be a `Sidekiq::Job`, it works well but we have used `ApplicationJob` in several jobs, and migrating them is our last resource if this is not going to be supported by `ApplicationJob` anymore.

We have also confirmed that using `RegeneratePassJob.perform_later(user_id)` works without any issue, it is only when using `Sidekiq::Client.push_bulk`

Will `ApplicationJob` be supported when using `Sidekiq::Client.push_bulk`?

Thanks,
Cesar.

---

Ruby version: 3.35
Rails version: 7.2.1
Sidekiq / Pro / Enterprise version(s): 7.3.7 - Enterprise 7.3.4

**Comment by mperham** [comment]
I'm not sure Active Job works with Sidekiq::Client.push_bulk. AJ has its own bulk enqueuing API which you should use. Can you see if that fixes the issue?

https://guides.rubyonrails.org/active_job_basics.html#bulk-enqueuing

On Wed, Jan 8, 2025, at 10:31, Cesar Navarro wrote:
> 
> 
> Upgrading from Sidekiq 7.2.x to 7.3.x and using `Sidekiq::Client.push_bulk` raises an error when executing the job.
> 
> We have code like this:
> 
> users.in_batches do |group|
>   ids = group.pluck(:id)
>   job_args = ids.map { |x| [x] }
>   Sidekiq::Client.push_bulk("class" => RegeneratePassJob, "args" => job_args)
> end
> The jobs are inserted well in the queue but when executing them raises the following error:
> 
> `pid=14550 tid=11d6 WARN: NoMethodError: undefined method `_context=' for an instance of RegeneratePassJob
`

**Comment by cenavarro** [comment]
Hi @mperham, 

We have been using `Sidekiq::Client.push_bulk` with ActiveJob for the past 4+ years and worked well until v7.3+.

I did a quick review of the changes and probably was introduced here: https://github.com/sidekiq/sidekiq/pull/6308/files#diff-60420f8c8f2d572be91e9b087d52becedcd44985559519c7ab3fc0989748151e

I will give it a try to AJ bulk enqueuing API. 

Also, let me know if `Sidekiq::Client.push_bulk` could be adjusted to work with AJ or if it was not designed to be used with classes rather than Sidekiq::Job ones.

Thanks for the quick reply.

**Comment by mperham** [comment]
In this case I think you should use the native bulk API, whether it's ActiveJob::Base or Sidekiq::Client.
